services:
  db:
    container_name: postgres-dealer
    image: postgres
    environment:
      POSTGRES_USER: mohammad_bakur
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "7000:5432"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: